Repository Zainveer02/hactoberfest1, pull requests merged in 2021-10, with the labels that each got.

#2 Create A program that had a class for both union find disjoint sets a…
  PUBLIC/A program that had a class for both union find disjoint sets and segment trees together.
Labels: enhancement, good first issue

#3 Create Merge Intervals
  PUBLIC/Merge Intervals
Labels: enhancement, good first issue

#4 Create tic tac toe with ai
  PUBLIC/tic tac toe with ai
Labels: enhancement, good first issue

#5 Create Chocolate Distribution Problem .cpp
  PUBLIC/Chocolate Distribution Problem .cpp
Labels: enhancement, good first issue

#6 Create Median of two sorted arrays.cpp
  PUBLIC/Median of two sorted arrays.cpp
Labels: enhancement, good first issue

#8 Create SHORTCODE.readme
  PUBLIC/SHORTCODE.readme
Labels: documentation, enhancement, good first issue

#9 Create Count triplets with sum smaller than X.cpp
  PUBLIC/Count triplets with sum smaller than X .cpp
Labels: enhancement

#10 Create Count number of elemengs in Linked List
  PUBLIC/Count number of elemengs in Linked List
Labels: enhancement

#13 Create duplicates_in_the_input_string.cpp
  PUBLIC/duplicates_in_the_input_string.cpp
Labels: enhancement, c++

#14 Create Split the Binary string into two substring with equal 0’s and…
  PUBLIC/Split the Binary string into two substring with equal 0’s and 1’s.cpp
Labels: enhancement, c++

#16 Create Rabin-Karp Algorithm for Pattern Searching.cpp
  PUBLIC/Rabin-Karp Algorithm for Pattern Searching.cpp
Labels: enhancement, c++

#18 Create Snake and Ladder.cpp
  PUBLIC/Snake and Ladder.cpp
Labels: enhancement, c++

#20 Create program to implement double hashing
  program to implement double hashing
Labels: c++

#21 Create C++ Program for FCFS
  C++ Program for FCFS
Labels: enhancement, c++
